### ISSUE TITLE
Error when running gulp in theme direcotry

### ISSUE THREAD

**Issue by sethburtonhall** [studiorabota/sage-twig-theme#9]
when I run `gulp` I get the following error

```
Error: Missing binding /Users/M8M/Sites/elon.dev/www/wordpress-default/wp-content/themes/sage-twig/node_modules/node-sass/vendor/darwin-x64-11/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node 0.10.x

Found bindings for the following environments:
  - OS X 64-bit with Node 0.12.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (/Users/M8M/Sites/elon.dev/www/wordpress-default/wp-content/themes/sage-twig/node_modules/node-sass/lib/index.js:14:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/M8M/Sites/elon.dev/www/wordpress-default/wp-content/themes/sage-twig/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

I have run `npm rebuild node-sass` but still get error

```
node -v
v0.12.7
```

```
npm -v
3.8.8
```

**Comment by studiorabota** [comment]
Hi @middle8media , I can't reproduce the issue locally. Did you try removing the `node_modules` folder and running 'npm install`? 

Otherwise it's best to ask this question at the node-sass Github - https://github.com/sass/node-sass/
